# Clé unique et nom du projet SonarQube / SonarCloud
sonar.projectKey=gestion-projets-m2
sonar.projectName=Gestion Projets M2 - Sécurisation
sonar.projectVersion=1.0

# Dépôt du code source à analyser
sonar.sources=.
sonar.exclusions=**/templates/**, **/static/**, **/*.db, **/*.tex, **/*.pdf, .venv/**, __pycache__/**

# Encodage du code
sonar.sourceEncoding=UTF-8

# Langage principal
sonar.language=py
sonar.python.version=3.13
